### ISSUE TITLE
SaltPad with subset of functionnality

### ISSUE THREAD

**Issue by arthurlogilab** [tinyclues/saltpad#23]
Am looking at saltpad to give access to some users to only a subset of the minions and a subset of salt commands. The documentation asks for an quite wide range of permissions : 

```
external_auth:
  pam:
    myusername:
        - .*
        - '@runner'
        - '@wheel'
```

How difficult do you think it would be to make saltpad to work with restricted access ? Two examples, give full access to a subset of the minions : 

```
external_auth:
  pam:
    myusername:
        - \*.staging.\*:
            - .*
```

Do all test.* on all minions (more realistically this would be mydeploy.* state) : 

```
external_auth:
  pam:
    myusername:
        - test.*
```

**Comment by Lothiraldan** [comment]
I've never used specific subset, I will give it a try.

Technically, the API return the permissions of the user at login, so we may be able to either manage them in saltpad or treat API permissions errors correctly and display them to the user.

Could you please test with specific permissions what happens when you try to make something like: salt -v '*' test.ping?

**Comment by arthurlogilab** [comment]
```
external_auth:
  pam:
    saltdev:
         - test.ping
```
on its own seem to make the salt-api fail on all commands, am pursuing this bug on https://github.com/saltstack/salt/issues/20246

Trying with saltpad
```
external_auth:
  pam:
    saltdev:
         - test.ping
         - '@runner'
         - '@wheel'
```

I can login, most links send me back to /log though (which is not ideal but at least it doesn't crash).

![screenshot from 2015-01-30 12 47 03](https://cloud.githubusercontent.com/assets/445200/5975275/e95c8fea-a87e-11e4-8af6-bf75528644d2.png)

(the "hi saltdev" followed by a login form is funny)

In /run I can do test.ping and get results which is promising. 

Side effect : the dynamic documentation fails on that screen and displays some html 

![screenshot from 2015-01-30 12 48 02](https://cloud.githubusercontent.com/assets/445200/5975271/dd992a4c-a87e-11e4-83e5-36fca590a9b3.png)

Do you want me to file separate issues for all these ?

**Comment by whiteinge** [comment]
> Could you please test with specific permissions what happens when you try to make something like: salt -v '*' test.ping?

The eauth check happens on the master before the command is sent out to minions. If you've only allowed access to a subset of your minions the target in the command must match the target in the eauth config.

E.g., with

```yaml
external_auth:
  auto:
    - 'web*':
      - test.ping
```

then `salt 'web*' test.ping` will work but `salt '*' test.ping` will be denied.

Rephrased: you must target only the minions you have access to target.

@Lothiraldan imo, you're definitely on the right track to have SaltPad parse the `perms` output after logging in in order to make the UI do/show only things that have the user has access to do/see.

**Comment by Lothiraldan** [comment]
Thank you @whiteinge for the analysis, I will try to play with permissions in the next weeks.

**Comment by arthurlogilab** [comment]
@whiteinge so this means that if a client (saltpad or pepper or another) wants to process "salt '*' test.ping" for a user and successfully send back the result for the 'web*' machines, then it has to convert 'salt '*' test.ping' to 'salt 'web*' test.ping' by looking at the perms send back by salt-api, am I getting this right ? 

It might be interesting to have this translation in a more core location so that developers of applications around salt-api don't have to re-implement every time this "security" translation.

**Comment by whiteinge** [comment]
@arthurlogilab I wouldn't suggest doing any kind of conversion. That might be misleading if a user thinks he can run something on `*` but is missing some minions in the return. I'd suggest sticking with regular Salt semantics in a way the improves the user experience.

Really it's up to the client. Whatever makes sense for the kind of application. For pepper that might be auto-completing hostnames at the CLI. For SaltPad that might be just a textual hint under the `target` and `function` fields that displays the current user's permissions. E.g., "You have permissions on the following hosts: X, Y, Z*". If SaltPad wanted to get complex about it, some kind of client-side error-checking could be performed before any HTTP requests were sent. But that's overly complicated for a first release, IMO.

**Comment by Lothiraldan** [comment]
@whiteinge What should we do about eauth configuration like this one:

```
external_auth:
  pam:
    dave:
      - test.ping
      - mongo\*:
        - network.*
      - log\*:
        - network.*
        - pkg.*
      - 'G@os:RedHat':
        - kmod.*
```

I agree with @arthurlogilab that implementing targeting logic in each client will be a wasting of time, I think one layer should convert the initial request `'*'` and select only allowed hosts.

Is it difficult to implement either in the API or in SaltStack itself?
