### ISSUE TITLE
Unable to authenticate in test setup with pam

### ISSUE THREAD

**Issue by harkx** [tinyclues/saltpad#51]
I followed the README and created a virtualenv for my test setup. The settings are:
```python
SECRET_KEY = 'xxxx'
HOST = "0.0.0.0"
EAUTH = "pam"
```
System is a Debian Wheezy. Saltpad is running on my master. Salt(-api) (2014.7.5) is configured to use pam, this part works when I use curl to authenticate and run commands.

When trying to login via saltpad (I get the login screen), I enter my user+pass and get returned to the login screen. (no error, it does display **Hi MyName**) 

The only error I can find is after enabling debug in the salt master:
`2015-04-27 13:05:55,147 [salt.master][WARNING ] Authentication failure of type "token" occurred for user MyName.`

I suppose I'm doing something wrong, can anyone lead me into the right direction?

**Comment by bbinet** [comment]
what is you `external_auth` configuration?
it should look like:
```
external_auth:
  pam:
    my_user:
      - .*
      - '@runner'
      - '@wheel'
```

**Comment by harkx** [comment]
Hi, yes, correct, this is in /etc/salt/master:

```
external_auth:
  pam:
    kristof:
      - .*
```
