### ISSUE TITLE
Jobs run as last logged in user

### ISSUE THREAD

**Issue by lukayeh** [tinyclues/saltpad#94]
Hi,

When running jobs in saltpad they do not run as the user you are currently log in as rather the last logged in user.

![2015-11-10 14_26_40-clipboard](https://cloud.githubusercontent.com/assets/12659390/11064775/2c81b15c-87b7-11e5-800e-abcc71b7775b.png)

As you can see in the screen shot that the logged in user is lpage but the job runs as jtennakoon.

Any ideas?

**Comment by Lothiraldan** [comment]
Did you launched the job via saltpad or via salt itself? Could you paste the external_auth configuration or at least the permission of the Ipage?

**Comment by lukayeh** [comment]
Hi @Lothiraldan 

We launched the job via saltpad, our external_auth looks like:

````
external_auth:
  pam:
    ahayes:
    - .*
    - '@wheel'
    - '@runner'
    amonitor:
    - .*
    gpaul:
    - .*
    - '@wheel'
    - '@runner'
    hbaxter:
    - .*
    - '@wheel'
    - '@runner'
    jtennakoon:
    - .*
    - '@wheel'
    - '@runner'
    lpage:
    - .*
    - '@wheel'
    - '@runner'
````
